- tasks/firewalld.yml
Replace version_compare with version(), version_compare was renamed in 2.5.
ref: https://docs.ansible.com/ansible/2.5/user_guide/playbooks_tests.html#version-comparison
> Change the version comparision syntax, foo|version_compare is deprecated

- README.md
In the `forward_port_by_mac` section you can find the "itentified
ba" typo, which should be replaced by "identified by".
> README: Fix "itentified ba" typo

- .github/workflows/tox.yml
- meta/main.yml
- molecule/default/Dockerfile.j2
- molecule/default/molecule.yml
- tasks/main.yml
Use the new vault.centos.org repos.  Fix the yum repo configs in the
image if necessary to use these new repos.
Use the standard centos images from the centos registry rather than
custom lsr images from dockerhub.
Add support for centos8.  Note that using ansible 2.7 on centos8 requires
setting /usr/bin/python3 to be the ansible python interpreter.  Later
versions of ansible have better auto-detection.  We can get rid of this
once we drop support for ansible 2.7
Use tox-lsr 1.0.1
> Fix centos6 repos; use standard centos images; add centos8

- README.md
- library/firewall_lib.py
- tasks/firewalld.yml
- tasks/main.yml
- tests/tests_zone.yml
The firewall role has been extended to be able to support the definition
of the zone a change is ensured on. A given zone will be used for these
parameters: `service`, `port` and `forward_port` without a given interface
or MAC address.
Also minor code cleanup has been done to enable the use of zones.
> firewall zone support with firewalld

- README.md
- library/firewall_lib.py
- tasks/main.yml
- tests/tests_connection.yml
The firewall role has been extended to be able to support the use of
connections where interfaces are supported at the moment. New variables
have been added for this:
- trust_by_connection
- masq_by_connection
- forward_port_by_connection
Depends on zone support changes (PR#14).
replaces https://github.com/linux-system-roles/firewall/pull/16
> firewall connection support with firewalld

- README.md
- library/firewall_lib.py
- tests/tests_ansible.yml
Adds support for user-created zones - user can add/remove zones.
Makes the role pass a.p.firewalld integration tests.
Code cleanup
Co-authored-by: Rich Megginson <rmeggins@redhat.com>
> support for user-created zones; pass a.p.firewalld tests

- library/firewall_lib.py
- tests/unit/test_firewall_lib.py
Fix module docs - minor updates
When setting `target` with `state: absent` or `state: disabled`, set value to `default`
Fix some failing unit tests
> fix module docs; set target to default for absent, disabled; fix unit tests

- library/firewall_lib.py
- tests/tests_target.yml
- tests/unit/test_firewall_lib.py
When changing the target, a reload is required in order for the
changes to take effect, so ensure that this happens.
The code has been refactored slightly in order to use the same
reload logic for other cases where reload is required.
A new test was added for the target use cases.
> ensure that changes to target take effect immediately

- tests/tests_ansible.yml
- Replaced all uses of the depreciated immediate option with the runtime option
Fixes: #77
> tests_ansible: replaced immediate options with runtime options

- library/firewall_lib.py
- tasks/main.yml
- tests/tests_ansible.yml
- tests/tests_purge_config.yml
- tests/tests_target.yml
- tests/unit/test_firewall_lib.py
- The above, and added a new error message for attempting to not specify state when using options that require state like source, port, port_forward
- Unit test case added for this error message
- Removed state option from integration tests for masquerading and ICMP block, retaining the same fail conditions
Fixes: #76
> fix: state not required for masquerade and ICMP block inversion

- README.md
- library/firewall_lib.py
- tasks/main.yml
- tests/tests_ansible.yml
- tests/tests_forward_port.yml
- fixed bug where port_forward argument only worked with string argument
- additionally argument converts to list if necessary
- minimal tests added for port forward
- tests_port_forward.yml only has the fail case that the role fails
Fixes: #85
> bugfix: port forward dict form works

- README.md
- library/firewall_lib.py
- tests/tests_interface_pci.yml
- tests/unit/test_firewall_lib.py
- Add/remove interfaces to a zone using PCI ID (formatted XXXX:XXXX, VendorID:DeviceID)
- Collision of interfaces with the same PCI ID (while unlikely) is handled by applying the play to each interface with the PCI id
- fixes RHBZ 2100939
- Useful as it allows control nodes to manage interfaces by what a device is rather than what interface name it was assigned.
- Added Network Manger interfacing in the same capacity to which firewall-cmd interacts with Network Manager for interfaces
- See `--[add/remove/change]-interface`  at https://firewalld.org/documentation/man-pages/firewall-cmd.html
> Add/remove interfaces to zone using PCI device ID

- examples/disable-cockpit-and-dhcpv6-client.yml
- examples/enable-http-and-https.yml
- examples/enable-ssh-only.yml
IMHO it's useful to have some example playbooks for common use cases that are easy to adapt by copy, paste, and modify.
I like it when roles have an example direktory with some playbooks in it, because it saves time when I don't have to search a long README.md for some examples.
With this PR I would like to contribute some example playbooks for the firewall role. I chose some use cases I encountered in different enviroments.
Signed-off-by: Joerg Kastning <jkastning@my-it-brain.de>
> Added some example playbooks

- .sanity-ansible-ignore-2.13.txt
- .sanity-ansible-ignore-2.14.txt
- library/firewall_lib.py
- tests/unit/test_firewall_lib.py
distutils is deprecated, and ansible-lint 2.14 throws an error about this.
There isn't really a suitable version parser replacement that works
without additional dependencies across python 2.7 - 3.11.  So, write
our own version parser.
> cannot use distutils; use custom version

- README.md
Add a note to the README about the use of `previous: replaced` and that it can
cause temporary service outages to the node being managed.
https://github.com/linux-system-roles/firewall/issues/138
> docs: Add note about using previous: replaced and temporary service failures

- pylintrc
Remove `no-space-check` and `overgeneral-exception`
> ci: fix pylintrc issues

- tasks/firewalld.yml
- vars/main.yml
Enhancement: The role now does not run tasks to install python-firewall or python3-firewall based on installed python version.
Reason:  python-firewall or python3-firewall is pulled automatically by dnf and yum when installing firewalld.
The issue is that when I install python3 on EL 7, the role then fails with "No package matching 'python3-firewall' found available, installed or updated". It sees python3 present on the system and tries to install python3-firewall, which is not available on EL 7.
Result: The role doesn't fail on EL 7 when python3 is installed on the managed node.
> fix: Don't install python(3)-firewall it's a dependency of firewalld

- .ansible-lint
- README.md
- library/firewall_lib.py
- tests/tests_service.yml
- tests/unit/test_firewall_lib.py
Enhancement:
- firewall_lib.py - check if service exists before running firewalld methods that would cause failure
- fails if service does not exist and in diff mode, warns if in check mode and service does not exist
- README.md - reflects changes and explains interaction with check mode
- tests/tests_service.yml - add integration test case for adding non-existent services in check mode
- tests/unit/test_firewall_lib.py - Mock necessary output from fw.config().getServiceNames()
Reason:
Better compliance with Ansible best practices for check mode (not failing in check mode, especially where they would not fail in diff mode)
Reason for this particular solution - We cannot track changes from previous check modes without overhauling how check mode is handled throughout the entire system role. …
> fix: make enabling/disabling non-existent services not fail in check mode

- README.md
- defaults/main.yml
- tasks/main.yml
- tests/tests_default.yml
- tests/tests_startup_conflicts.yml
- vars/main.yml
Enhancement:
Role will now always attempt to unmask on role execution
add variable 'firewall_disable_conflicting_services' to give the option of disabling of known conflicting services
- Set to false by default
Update README to document the following behavior of the system role:
- linux-system-roles.firewall will attempt to install, unmask, and enable firewalld
- linux-system-roles.firewall can attempt to disable directly conflicting services to firewalld
- and that is enabled by setting the variable 'firewall_disable_conflicting_services' to true
- list of conflicting services present in vars/main.yml
test cases for these changes in tests/tests_default.yml
Reason:
role currently fails if firewalld was masked on run
conflicting services have the potential to cause errors on role run
- set …
> fix: unmask firewalld on run, disable conflicting services

- tasks/firewalld.yml
- vars/main.yml
Cause: The comparison of the present facts with the required facts is
being done on unsorted lists.
Consequence: The comparison may fail if the only difference is the
order.  Facts are gathered unnecessarily.
Fix: Use `difference` which works no matter what the order is.  Ensure
that the fact gathering subsets used are the absolute minimum required.
Result: The role gathers only the facts it requires, and does
not unnecessarily gather facts.
> fix: facts being gathered unnecessarily

- README.md
- library/firewall_lib.py
- tasks/main.yml
- tests/tests_firewalld_conf.yml
- tests/unit/test_firewall_lib.py
Enhancement:
firewall varable option firewalld_conf added to support modifying supported firewalld_conf arguments
- Sub-argument allow_zone_drifting modifies AllowZoneDrifting if possible via dbus
- This should be supported in EL7+ due to backporting
- Associated Documentation added
- Unit tests for feature added to tests/unit/test_firewall_lib.py
- Integration test for feature in tests/tests_firewalld_conf.yml
Reason:
Many EL releases for firewalld set `AllowZoneDrifting=yes` as the default. This feature allows those who do not want this insecure feature set to disable the feature using the role.
Result:
AllowZoneDrifting can be changed to whatever the role user wants to change it to, provided it is not deprecated.
Will fail if the system is using a version of firewalld where …
> feat: add new arg firewalld_conf, subarg allow_zone_drifting

- files/get_files_checksums.sh
- tasks/main.yml
- vars/main.yml
Cause: The role was not checking to see if any files would be
changed when using `previous: replaced` in check mode.  The variables
that should have been set were not set in check mode.
Consequence: The role would give an error about undefined variables.
Fix: A new check has been added for check mode, to see if any files
would be changed by `previous: replaced`.  The check for
`firewalld.conf` looks at the rpm database to determine if the file
has been changed from the version shipped in the package.  If files
would not be changed by using `previous: replaced`, then the role
will also now correctly report if any settings would be changed.
Result: The role works in check mode when using `previous: replaced`
> fix: error when running with check mode and previous: replaced

- tests/tests_ansible.yml
- tests/tests_firewall_fact.yml
In tests_ansible - save and restore default zone
In tests_firewall_fact - ensure default zone did
not change instead of hardcoded `public` zone
> test: tests_ansible zone cleanup; check for default zone

- library/firewall_lib.py
- tests/tests_ansible.yml
- tests/unit/test_firewall_lib.py
Enhancement:
Make try_set_zone_of_interface in library/firewall_lib.py return a second value, which denotes whether the interface's zone was changed.
Reason:
Network Manager interface assignment reported changed when no changes were present
Result:
The module now properly reports changes when assigning zones to interfaces handled by Network Manager.
Issue Tracker Tickets (Jira or BZ if any):
- Jira - RHEL-885
> fix: firewall_lib: make try_set_zone_of_interface idempotent

- tests/files/test_ping.sh
- tests/tests_reload_on_reset.yml
Test script no longer fails if managed node does not support podman network create --interface name
Enhancement:
- Removed unnecessary imports from Containerfile generated by tests/files/test_ping.sh
- Removed usage of --interface-name from podman network create in test_ping.sh (and removed usage of podman network create in general, since that is also unnecessary for the purposes of the test)
Reason:
test fails on some platforms (RHEL 8.8, 9.2) due to podman not supporting `podman network create --interface-name` option
Result:
Tests pass on managed nodes with podman versions < v4.4
> tests: test_ping: fix compatability issues

- files/get_files_checksums.sh
- tests/tests_purge_config.yml
on previous replaced, revert firewalld.conf to fallback configuration instead of deletion
Enhancement:
Replaces firewalld.conf on previous replaced instead of deleting when changed
Reason:
EL7+ firewalld releases appeared to support a fallback configuration in firewalld, which could be effectively used to override the previous configuration.
Result:
On reset, firewalld.conf is not deleted, and comments in the file are retained.
Addresses GitHub issue #164
> fix: files: overwrite firewalld.conf on previous replaced

- .ostree/get_ostree_data.sh
- meta/collection-requirements.yml
- tasks/firewalld.yml
- tests/tests_reload_on_reset.yml
- tests/tests_startup_conflicts.yml
The dependency on `ansible.utils.update_fact` is causing issue with
some users who now must install that collection in order to run
the role, even if they do not care about ostree.
The fix is to stop trying to set `ansible_facts.pkg_mgr`, and instead
force the use of the ostree package manager with the `package:` module
`use:` option.  The strategy is - on ostree systems, set the flag
`__$ROLENAME_is_ostree` if the system is an ostree system.  The flag
will either be undefined or `false` on non-ostree systems.
Then, change every invocation of the `package:` module like this:
```yaml
- name: Ensure required packages are present
package:
name: "{{ __$ROLENAME_packages }}"
state: present
use: "{{ (__$ROLENAME_is_ostree | d(false)) |
ternary('ansible.posix.rhel_rpm_ostree', omit) }}"
```
This …
> refactor: improve support for ostree systems

- .markdownlint.yaml
- .sanity-ansible-ignore-2.12.txt
- .sanity-ansible-ignore-2.13.txt
- .sanity-ansible-ignore-2.14.txt
- .sanity-ansible-ignore-2.15.txt
- .sanity-ansible-ignore-2.9.txt
- files/get_files_checksums.sh
- library/firewall_lib.py
- tests/files/test_ping.sh
The old ansible-community ansible-lint is deprecated.  There is a
new ansible-lint github action.  The new ansible-lint has several checks
related to ansible-test and the ignore files.  Many of our ignore settings
are not allowed any more and are required to be fixed or addressed in the
Ansible preferred way.
The module documentation must comply with the Ansible standards.
The result of this is that the .sanity files can be reduced to the
bare minimum which will greatly reduce the maintenance burden of
those files, make it easier to support newer versions of Ansible,
and make it easier to import the system roles collection into Galaxy
and Automation Hub.
The latest Ansible repo gating tests run ansible-lint against
the collection format instead of against individual roles.
We have to …
> ci: Use supported ansible-lint action; run ansible-lint against the collection

- README.md
- tasks/firewalld.yml
Enhancement: Add Conditional Reboot and README.md Syntax Fix
Reason: To support transactional update systems that require a reboot for changes to take effect and to correct a syntax error in the firewall configuration example in the readme.md.
Result: Ensures that changes on transactional systems are applied correctly if a new package is installed.
Issue Tracker Tickets (Jira or BZ if any):na
> ci: Add conditional reboot for transactional update support

- tasks/firewalld.yml
Enhancement: Redundant reboot task.
Reason: Removing unnecessary reboot task
Result: system will not reboot after package install
Issue Tracker Tickets (Jira or BZ if any):na
> ci: Remove redundant reboot task

- .github/workflows/ansible-lint.yml
- .github/workflows/ansible-managed-var-comment.yml
- .github/workflows/ansible-plugin-scan.yml
- .github/workflows/ansible-test.yml
- .github/workflows/python-unit-test.yml
- .yamllint.yml
- library/firewall_lib_facts.py
The latest version of virtualenv does not support creating
python 2.7 virtualenvs.  Change our CI tests to restrict the version
of virtualenv<20.22.0 and tox<4.15 for py27 environments
Move pylint, flake8, and black checks to the py310 environment
which is currently supported by ansible-core 2.17 and its related
checkers such as ansible-lint and ansible-test
pylint now uses ansible-core 2.17 and restricts the version of
pylint to 3.1.0 which is the version used by ansible-test 2.17
Remove `extends: default` for .yamllint.yml.  The latest version
of ansible-lint will automatically incorporate local yamllint
settings unless there is an `extends:`.
The above changes require some fixes to the role code.
For more information, see
https://github.com/linux-system-roles/tox-lsr/pull/168
and …
> ci: tox-lsr 3.4.0 - fix py27 tests; move other checks to py310

- README.md
- defaults/main.yml
- tasks/firewalld.yml
Enhancement: - Added a block to handle reboots for transactional update systems on firewall package changes. Update README.
Reason: Ensure necessary reboots are managed, as changes on transactional update systems are applied in a separate snapshot and require a reboot to take effect.
Result: Manages system reboots for transactional update systems when package is installed.
Issue Tracker Tickets (Jira or BZ if any):na
> feat: Handle reboot for transactional update systems

- library/firewall_lib.py
- tests/unit/test_firewall_lib.py
Cause: The module was replacing the `changed` value with `False` when using `interface` and the interface exists.
Consequence: The role reported `changed: False` even when there were changes, and `forward_ports` were not being saved as permanent.
Fix: Ensure the `changed` value is not reset to `False` in this case.
Result: The role reports `changed: True` when there are changes, and `forward_ports` settings are persistent.
This fixes #234
> fix: Prevent interface definitions overriding 'changed' value when other elements are changed

- README.md
- library/firewall_lib.py
- tasks/main.yml
- tests/tests_ansible.yml
- tests/tests_service.yml
Feature: Allow for includes to be specified for services.
Includes are described at https://firewalld.org/documentation/man-pages/firewalld.service.html
Reason: This makes firewalld services more explicit and easier / quicker
to read when there are many non-standard ports.
Result: Users can specify other services to include when creating
and setting services.
Fixes https://github.com/linux-system-roles/firewall/issues/255
> feat: support includes for services

- .github/workflows/qemu-kvm-integration-tests.yml
Some roles produce ansible/test logs which are too large to sensibly/comfortably view in the main workflow log view. Show only the interesting failures there (the lines around `fatal:`) and upload the full logs as artifact.
---
See [recent run](https://github.com/linux-system-roles/firewall/actions/runs/14405081081/job/40399563001) for example. The primary PR for this is https://github.com/linux-system-roles/.github/pull/99 , this tests it against a real-life project with a failing F42 test.
> ci: Avoid too large inline test logs in QEMU/KVM integration test

- .github/workflows/ansible-lint.yml
- .github/workflows/ansible-managed-var-comment.yml
- .github/workflows/ansible-test.yml
- .github/workflows/python-unit-test.yml
- .github/workflows/qemu-kvm-integration-tests.yml
- .ostree/packages-testing.txt
- meta/main.yml
- tests/tests_reload_on_reset.yml
Same as in https://github.com/linux-system-roles/sudo/pull/52 to check the new mechanics for a more complex role. This is a case where the role works fine in a system container, but *not* yet during a bootc container build. I'm working on that in my https://github.com/martinpitt/lsr-firewall/tree/bootc-container-test branch, see https://issues.redhat.com/browse/RHEL-88425 . But this is a nice stepping stone.
> ci: Add container integration test for rpm and bootc

- README.md
- tests/tests_ansible.yml
- tests/tests_service.yml
The new `includes` feature is only supported on EL8 and above, not
on EL7.  Document this.  Skip testing includes on EL7.
> test: skip include tests on el7, document el7 support

- .README.html
- CHANGELOG.md
Update changelog and .README.html for version 1.9.1
> docs(changelog): version 1.9.1 [citest skip]

- tests/tests_firewall_fact.yml
Spot-check a particular entry of each fact group (helpers, icmptypes, policies, services, and zones) to ensure the returned fact structure is as expected. This will help with validating a future `firewall-offline-cmd` backend.
Also check that the service addition and custom service creation actions are actually reflected in the facts.
> ci: Assert fact structure and some well-known entries

- .github/workflows/ansible-lint.yml
- .github/workflows/ansible-managed-var-comment.yml
- .github/workflows/ansible-test.yml
- .github/workflows/build_docs.yml
- .github/workflows/changelog_to_tag.yml
- .github/workflows/codeql.yml
- .github/workflows/codespell.yml
- .github/workflows/markdownlint.yml
- .github/workflows/pr-title-lint.yml
- .github/workflows/python-unit-test.yml
- .github/workflows/qemu-kvm-integration-tests.yml
- .github/workflows/shellcheck.yml
- .github/workflows/test_converting_readme.yml
- .github/workflows/tft.yml
- .github/workflows/tft_citest_bad.yml
- .github/workflows/weekly_ci.yml
- .github/workflows/woke.yml
- contributing.md
- plans/test_playbooks_parallel.fmf
* Pass in a YAML true value as `__bootc_validation: true` using
the --extra-vars option to ensure that `__bootc_validation` is
treated as a boolean and not a string value.
`-e "__bootc_validation: true"`
You can also use JSON format:
`-e '{"__bootc_validation": true}'`
but YAML is simpler in this case.
* Use tox-lsr version 3.11.1
* Ensure the citest bad comment works when the test was cancelled in
addition to the failure case.
* Update contributing.md documentation
* Update number of nodes to use in testing farm, if needed
* remove unnecessary ansible-lint skips
> ci: rollout several recent changes to CI testing
